



const roles = ['guest', 'host', 'admin'];

// const states = ['Karnataka'];

// src/constants/states.js
// const STATE_CODES = Object.freeze({
//   "andhra_pradesh",
//   "arunachal_pradesh",
//   "assam",
//   "bihar",
//   "chhattisgarh",
//   "delhi",
//   "goa",
//   "gujarat",
//   "haryana",
//   "himachal_pradesh",
//   "jammu_and_kashmir",
//   "jharkhand",
//   "karnataka",
//   "kerala",
//   "madhya_pradesh",
//   "maharashtra",
//   "manipur",
//   "meghalaya",
//   "mizoram",
//   "nagaland",
//   "odisha",
//   "punjab",
//   "rajasthan",
//   "sikkim",
//   "tamil_nadu",
//   "telangana",
//   "tripura",
//   "uttar_pradesh",
//   "uttarakhand",
//   "west_bengal",
// });

const STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
];


// const STATE_CODES = Object.freeze(Object.keys(STATE_MAP));

const AMENITIES = [
  'WiFi',
  'Air Conditioning',
  'Heating',
  'Kitchen',
  'Refrigerator',
  'Microwave',
  'Oven',
  'Stove',
  'Dishwasher',
  'Washing Machine',
  'Dryer',
  'Television',
  'Cable TV',
  'Streaming Services',
  'Workspace / Desk',
  'Parking',
  'Balcony',
  'Terrace',
  'Garden',
  'Private Pool',
  'Shared Pool',
  'Hot Tub',
  'Gym',
  'Elevator',
  'Wheelchair Accessible',
  'Pet Friendly',
  'Smoking Allowed',
  'Non-Smoking Rooms',
  'Security / CCTV',
  'First Aid Kit',
  'Fire Extinguisher',
  'Smoke Alarm',
  '24/7 Check-in',
  'Housekeeping',
  'Room Service',
  'Breakfast Included',
  'Restaurant On-site',
  'Bar On-site',
  'Playground',
  'Children’s High Chair',
  'Crib / Baby Cot',
  'Board Games',
  'Library / Books',
  'Bicycle Rental',
  'Car Rental',
  'Airport Shuttle',
  'Beach Access',
  'Mountain View',
  'City View',
  'Lake View',
  'Temple/Heritage Nearby',
];



export { roles, STATES, AMENITIES };
